global class NowDealClosedBy {
//Waiting to Delete
/*
    public static void setNowDealClosedBy(List<Account> accountsInTrigger) {
        for (Account account : accountsInTrigger) {
          if (account.Now_Deal_Closed_By__c == null && account.Now_Deal_Owner__c != null && account.Now_Status__c == 'closed won') {
            account.Now_Deal_Closed_By__c = account.Now_Deal_Owner__c;
          }
        }
    }
*/
}