global class PreviousAccountData {
//Waiting to Delete
/*
    public static void setPreviousAccountOwner(List<Account> accountsInTrigger, Map<Id,Account> triggerNewMap, Map<Id,Account> triggerOldMap) {
        for (Account account : accountsInTrigger) {
            Id oldOwnerId = triggerOldMap.get(account.Id).OwnerId;
            if (oldOwnerId != account.OwnerId) {
              account.Previous_Account_Owner__c = oldOwnerId;
            }
        }
    }
    
    public static void setPreviousAccountStatus(List<Account> accountsInTrigger, Map<Id,Account> triggerNewMap, Map<Id,Account> triggerOldMap) {
        for (Account account : accountsInTrigger) {
            String oldAccountStatus = triggerOldMap.get(account.Id).Account_Status__c;
            if (oldAccountStatus != account.Account_Status__c) {
                account.Previous_Acct_Status__c = oldAccountStatus;
            }
        }
    }
*/
}