global class SetRewardsOfferStatus {
//Waiting to Delete
/*
    public static void updateRewardsOfferStatus(List<Account> accountsInTrigger,Set<Id> triggerNewId) {
        rewardsOfferStatus ros = new rewardsOfferStatus(triggerNewId);
    
        for (Account account : accountsInTrigger) {
            account.Rewards_Offer_Status__c = ros.offerStatus.get(account.Id);            
        }
    }
*/
}