@isTest
private class testACHcheckSum {
//Waiting to Delete
/*
    static testMethod void myUnitTest() {
        Account a1 = new Account(name='achAcct Test Ipsum' + system.now(), BillingCountry='US', eligibility__c='Eligible', Tax_Identification_Number__c ='12345', Routing_Number_enc__c ='789456124', Account_Number__c = '987654321', Payment_Preference__c='ACH (Direct Deposit)');
        Account b1 = new Account(name='AcctACH Test Dolor' + system.now(), BillingCountry='US', eligibility__c='Eligible', Tax_Identification_Number__c ='12345', Routing_Number_enc__c ='789456121', Payment_Preference__c='ACH (Direct Deposit)');
        Account c1 = new Account(name='achAcct Test sit' + system.now(), BillingCountry='CA', eligibility__c='Eligible', Tax_Identification_Number__c ='12345', TransitNumber__c  ='12345678', Payment_Preference__c='ACH (Direct Deposit)');
        Account d1 = new Account(name='achAcct Test amet' + system.now(), BillingCountry='US', eligibility__c='Eligible', Tax_Identification_Number__c ='12345', Payment_Preference__c='Check');
        
        insert a1;
        insert b1;
        insert c1;
        insert d1;
        
        a1.Routing_Number_enc__c = '789456122';
        a1.BillingCountry = 'CA';
        a1.Account_Number__c = '123456789';
        update a1;
        //list<account> ValidAcctTest = [select id, name, Valid_Routing__c from Account where name = 'a1'];
        //list<account> InValidAcctTest = [select id, name, Valid_Routing__c from Account where name = 'b1'];
    }
*/
}